# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: dotnet-sdk
    directories:
      - /
    schedule:
      interval: monthly
    labels: []
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: monthly
    labels: []
  - package-ecosystem: nuget
    directories:
      - /
    schedule:
      interval: monthly
    labels: []
